name: realtime_chatapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.24.2
  google_fonts: ^6.1.0
  intl: ^0.19.0
  gap: ^3.0.1
  hexcolor: ^3.0.1
  firebase_database: ^10.4.0
  google_sign_in: ^6.1.6
  firebase_auth: ^4.16.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

